### ISSUE TITLE
Potential in compatibility issue with existing ecoinvent dataset (v3.8)

### ISSUE THREAD

**Issue by xiaoshir** [polca/premise_gwp#2]
Hi, I saw by installing this premise_gwp, the flow "Carbon dioxide, in air" is characterized with -1. But I noticed that in some ecoinvent datasets for Brazil, for example dataset "land already in use, pasture, man made to perennial crop" from "BR-SP", it is weirdly modeled with both "Carbon dioxide, to soil or biomass stock" and "Carbon dioxide, in air" and they share the same amount, indicating the author of this dataset probably wanted to use such way of modelling to say the CO2 is absorbed from the air to the soil. But if we characterize "Carbon dioxide, in air" in addition to "Carbon dioxide, to soil or biomass stock" with -1, this dataset will end up having absorbed the same amount of CO2 twice. See below:
![image](https://user-images.githubusercontent.com/28433916/182362529-132594ed-f936-454e-8f90-399578752c22.png)

**Comment by romainsacchi** [comment]
Indeed. That's probably something to report to ecoinvent.

**Comment by romainsacchi** [comment]
I reported this issue to ecoinvent. They will check it. I close this issue. I think "Carbon dioxide, to soil or biomass stock" should be "Carbon dioxide, from soil or biomass stock" because what this dataset represents is the clear-cutting of primary forest (hence, change in carbon storage). Anyway, ecoinvent will let us know.
